apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/mjunx/dependency-track:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/mjunx/dependency-track:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: dependency-track
        chartPath: charts/dependency-track
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/mjunx/dependency-track"
          image.tag: "{{.DIGEST_HEX}}"
